### ISSUE TITLE
Update Architecture Diagram

### ISSUE THREAD

**Issue by OzHawk** [rtrussell/BBCSDL#13]
Update the architecture diagram to include the Raspberry Pi Pico version.

**Comment by rtrussell** [comment]
Architecturally the Pico edition is no different from the other Console Mode builds.  The only difference is that rather than trying to merge the Pico-specific code into the generic **bbccon.c** there is a separate source file **bbpico.c**.  I have amended the [architecture diagram](https://www.bbcbasic.co.uk/bbcsdl/arch.png) to include that file for completeness, although I would not want that to set a precedent for other Microcontroller versions because it could get too cluttered.

I don't know how to force README.md to refresh its cache of the diagram.  Perhaps it just needs time.
