### ISSUE TITLE
Document Development Environments

### ISSUE THREAD

**Issue by OzHawk** [rtrussell/BBCSDL#14]
Sorry to keep raising issues, but it seems to be the only way to discuss things regarding a project.
I would really like to contribute to the project, but I'm uncertain of the development environment.
I have been trying to learn to use PlatformIO within Visual Studio Code as an IDE for microcontroller development, but understand that this may not be appropriate for the SDL development.
What is the recommended development environment?
What tools do I need to have installed?
What libraries do I need installed?
Thanks.

**Comment by rtrussell** [comment]
I prefer not to be prescriptive about development environments because that's very much a matter of personal taste.  The code does rely on GCC extensions, which are also supported in Clang, so it's unlikely to compile successfully using other compilers including Microsoft's.  For the record these are what I use for the various editions:

- Windows: mingw with a regular makefile
- MacOS: Xcode command-line tools with a regular makefile
- Linux/Rpi: standard command-line tools with a makefile
- Android: Android Studio IDE running on Windows
- iOS: Xcode IDE running on MacOS
- Browser: Emscripten command-line tools

I've not tried to build the Pico edition myself but I presume it just requires the standard [Pico SDK](https://raspberrypi.github.io/pico-sdk-doxygen/).

Generally the makefile (for those editions which use one) will list any libraries you need.

**Comment by OzHawk** [comment]
Thanks Richard. I’m looking at an ESP32 version, but maybe I should learn to build one of the other versions first.
Maybe what you stated just then needs to be in a build document.  The specific tools for each platform could be elaborated on a bit more.
