### ISSUE TITLE
libtop is not being correctly updated when HIMEM is lowered

### ISSUE THREAD

**Issue by Memotech-Bill** [rtrussell/BBCSDL#17]
The variable libtop is not being correctly updated when HIMEM is lowered with no libraries installed. My suggested modification to the code in bbexec.c is:

            case THIMEML:
                {
                equals () ;
                void *n = (void *) (size_t) (expri () & -4) ; // align
                if ((n < (pfree + zero + STACK_NEEDED)) ||
                        (oshwm (n, 1) == 0))
                    error (0, NULL) ; // 'No room'
                if ((void *) esp == himem + zero)
                    esp = n ;
                himem = n - zero ;
                if ((libase != 0) && (himem > libase))
                    {
                    libase = 0 ;
                    proptr[0] = 0 ;
                    fnptr[0] = 0 ;
    #ifdef PICO
                    libtop = n ;
                    }
                else if (libase == 0)
                    {
                    libtop = n;
    #endif
                    }
                }
                break ;

I found cases where on the Pico implementation the machine stack was running into libtop without being detected by the test in bbexec.c. I suggest adding another check in the expression evaluator in bbeval.c:

	while (1) // for each statement
	    {
    #ifdef PICO
		if((&al < (signed char *)libtop + 0x800) && (&al >= (signed char *)userRAM))
			error(62, "Recursion too deep!");
    #endif
	 	if (flags & (KILL + PAUSE + ALERT + ESCFLG))

In order to implement *refresh for the Pico GUI version it is necessary insert a call where that command is recognised in bbccos.c:

    #ifdef PICO_GUI
    void refresh (const char *p);
    #endif
        :
        :
            case REFRESH:
    #ifdef PICO_GUI
                refresh (p);
    #endif
                return ;

**Comment by rtrussell** [comment]
> The variable libtop is not being correctly updated when HIMEM is lowered with no libraries installed.

That is by design.  My thinking was as follows: the most likely reason for wanting to **lower** HIMEM from its initial value is to provide 'static' space to store something that will be retained when a new program is loaded, typically data that needs to be shared between modules.  The gap between the old HIMEM and the new HIMEM is therefore **not** somewhere that it is safe for the machine stack to overflow into, so libtop should not be changed.

The only situation I can think of when one might want to lower HIMEM and **also** lower libtop is in order to allow deeper recursion.   The trouble is that the interpreter has no way of telling **which** is the actual reason, so one has to make a judgement.  The clinching argument, as far as I'm concerned, is that lowering HIMEM to make space for shared data is something that has been supported in BBC BASIC for 40 years, whereas providing more space for recursion is peculiar to the Pico.

A related argument is that lowering HIMEM does not provide more space for libraries, so why should it make more space for the machine stack?   And indeed if any libraries are loaded, your proposed modification won't allow the recursion depth to be increased anyway.   So I am not in favour of making this change, unless there's something I've missed.

> I found cases where on the Pico implementation the machine stack was running into libtop without being detected
> by the test in bbexec.c. I suggest adding another check in the expression evaluator in bbeval.c:
> ...
> In order to implement *refresh for the Pico GUI version it is necessary insert a call where that command is recognised
>  in bbccos.c:

These are unrelated to the above, so to aid version control I would prefer them to be raised as separate issues.

**Comment by Memotech-Bill** [comment]
> A related argument is that lowering HIMEM does not provide more space for libraries, so why should it make more space for the machine stack?

The first library to be loaded is loaded at HIMEM, so lowering HIMEM does provide more space for libraries.

> And indeed if any libraries are loaded, your proposed modification won't allow the recursion depth to be increased anyway.

Agreed. The user has to decide how much space above HIMEM is required before making use of any of it, be that for libraries, refresh buffers or other use.

There is a case for two separate variables:

* libtop - The top of space used by libraries. Perhaps zero (like libbase) if no libraries loaded.
* stkchk - The limit used for stack checking. There does need to be some way for the user to influence this if they need to provide more room for recursion or expression evaluation.

**Comment by rtrussell** [comment]
> There does need to be some way for the user to influence this if they need to provide more room for recursion
> or expression evaluation.

I can't agree that there "needs" to be; there will always be constraints and if one of those is that there is a maximum size of stack which if exceeded will cause the interpreter to crash, so be it.  If the user's program can be adapted to reduce stack usage great, if it can't it won't run.  Providing a means to increase the machine stack space is **not** in the BBC BASIC contract!

The default memory map allocates up to about 64K for the stack and that ought to be plenty: the equivalent memory in the BBC Micro is 256 bytes!  The only reason this is proving to be an issue at all is that compiled C appears to use hugely more stack than comparable assembly language code would; I've never had cause to be aware of this on other platforms because of on-demand paging of virtual memory being able to make plenty of stack available.

If one looks to other versions of BBC BASIC for a precedent, the most similar situation I know of is in _BBC BASIC for Windows_ which has a configuration option for setting the initial value of HIMEM (Options... Customize... Initial user memory).  Providing such a configuration option for **all** the console mode editions, not just the Pico, (perhaps by means of a config file) is an approach I would consider.

**Comment by Memotech-Bill** [comment]
Looking for other options as to where to allocate memory, do variables move once they are allocated? What happens to variables if a program is edited?

**Comment by rtrussell** [comment]
> Looking for other options as to where to allocate memory, do variables move once they are allocated?
> What happens to variables if a program is edited?

Variables don't move (if they did, one wouldn't be able to use pointers to variables!).  Editing a program implies doing a CLEAR (destroying all variables) which is why BBC BASIC doesn't have a RESUME keyword: you can't continue execution after editing or an untrapped error.  This irritates people used to Microsoft BASICs!

**Comment by rtrussell** [comment]
I am deleting the Pico-specific stuff from this repository, therefore this issue has become irrelevant.
