### ISSUE TITLE
Stack check required in expression evaluation

### ISSUE THREAD

**Issue by Memotech-Bill** [rtrussell/BBCSDL#18]
I found cases where on the Pico implementation the machine stack was running into libtop without being detected by the test in bbexec.c. I suggest adding another check in the expression evaluator in bbeval.c:

	while (1) // for each statement
	    {
    #ifdef PICO
		if((&al < (signed char *)libtop + 0x800) && (&al >= (signed char *)userRAM))
			error(62, "Recursion too deep!");
    #endif
	 	if (flags & (KILL + PAUSE + ALERT + ESCFLG))

**Comment by rtrussell** [comment]
> I suggest adding another check in the expression evaluator in bbeval.c:

I'm confused; the code you listed doesn't appear to be from **bbeval.c**, unless I'm mistaken it looks to be the existing code from **bbexec.c**?

Under what circumstances (other than something contrived) have you encountered a machine stack overflow in the expression evaluator?  Whereas recursive code can use an arbitrarily large amount of stack, the maximum depth of nesting within an expression is constrained.

Because it's such a critical part of the interpreter from the point of view of execution speed, I'd prefer simply to ensure that there's enough stack space for a reasonable depth of nesting within an expression, rather than add a run-time check.  If you do something deliberately silly like:

      PRINT (((((((((((((((((((((((((((((((PI)))))))))))))))))))))))))))))))

I think crashing is a reasonable outcome!

But if you do think a run-time check is the only acceptable solution, it would need to be placed carefully so as to have no effect on an expression that doesn't actually use nesting.  Slowing down a trivial expression (such as a constant or variable) wouldn't be acceptable to me.

Incidentally we discovered early on that optimisation level had an unexpected and counter-intuitive effect on stack usage (higher optimisation sometimes using more stack).  Is your makefile definitely set up to keep stack usage to a minimum, consistent with performance?  Do we know how later compilers (e.g. GCC 10, which I understand will not compile BBC BASIC currently) compare in respect of stack usage?

**Comment by Memotech-Bill** [comment]
When testing "bounce.bbc" I was seeing clear corruption of the second framebuffer without hitting the limit set in bbexec.c. I eventually concluded that the stack was getting lowest in bbeval.

Yes the format of the check is identical in bbeval.c and bbexec.c. A coincidence that they both have local variables called al.

Is the check really much of a cost, it is just a comparison between two pointers? the subroutine call only occurs if the check fails.

**Comment by rtrussell** [comment]
> I eventually concluded that the stack was getting lowest in bbeval.

It's quite likely that the stack will reach its **lowest** limit there, but that's not a reason to **test** it there.  My approach would be to estimate a reasonable upper limit for the amount of stack used by the expression evaluator, and then in the stack check (in bbexec.c) make sure that enough free stack space is still available.  It doesn't eliminate the possibility of an undetected overflow, but it reduces the likelihood.

That is similar to the approach taken in the rest of the interpreter for detecting an overflow of the interpreter's soft stack.  Rather than doing a check whenever something is pushed on the stack, which would be wasteful and time consuming, a check is made only occasionally but it ensures that there is at least STACK_NEEDED free space left.  This is hopefully enough for all the 'unchecked' pushes that might happen before the next check.

> Yes the format of the check is identical in bbeval.c and bbexec.c. A coincidence that they both have local variables
> called al.

I searched the code of **bbeval.c** for "_while (1) // for each statement_" and it doesn't exist anywhere.  I still think you listed code from **bbexec.c** by mistake.

> Is the check really much of a cost, it is just a comparison between two pointers? the subroutine call only occurs
> if the check fails.

A comparison between two pointers could add a significant overhead if, for example, there are no free registers left and the compiler needs to evict a local variable to the stack (making the stack growth even worse!).  You will know from your work on the assembler that many CPU instructions can only directly access 8 registers, so register pressure can be severe.  Nevertheless I'd like to see what your actual proposal is, because if it only does the check when nesting actually happens (e.g. on encountering a parenthesis) it may be acceptable.

**Comment by Memotech-Bill** [comment]
Apologies, must have been a copy-paste error. My modification is:

    VAR item (void)
    {
        VAR v ;
        signed char al = nxt () ;
    #ifdef PICO
        if((&al < (signed char *)libtop + 0x800) && (&al >= (signed char *)userRAM))
            {
            error(0, "Expression evaluation too deep!");
            }
    #endif
        errno = 0 ;
        esi++ ;
        switch (al)

**Comment by rtrussell** [comment]
> Apologies, must have been a copy-paste error. My modification is:

I suggest you compare the results from **timing.bbc** (you need to be patient on the Pico!) before and after the modification, so we can quantify just what impact it has.

>         error(0, "Expression evaluation too deep!");

That is potentially misleading.  The error doesn't necessarily indicate that expression evaluation is too deep, but simply that the overflow happened to occur in the expression evaluator.  The actual cause is more likely to be the use of recursion, but which happened to be picked up here first.   Similarly if the cause is deep expression evaluation which includes a function call, it might be detected in **bbexec.c** first.

If there are two places in the code where the stack check is made (bbexec.c and bbeval.c)  they should report the same generic error because it's not possible to distinguish anything useful to the programmer from which happens to detect the overflow first.

**Comment by Memotech-Bill** [comment]
Timing results with and without the stack check in bbeval.c

                                With       Without     Ratio
                               -------    --------    -------
    Colon:                      534 ns      539 ns     99.07%
    Dispatch (ENDCASE):         850 ns      859 ns     98.95%
    Dispatch (ENDIF):           931 ns      941 ns     98.94%
    NEXT (integer):            2897 ns     2928 ns     98.94%
    NEXT (default real):       6651 ns     6698 ns     99.30%
    NEXT (64-bit real):        6690 ns     6713 ns     99.66%
    NEXT N%:                   4199 ns     4244 ns     98.94%
    NEXT n%:                   5537 ns     5653 ns     97.95%
    NEXT N:                    9071 ns     9196 ns     98.64%
    NEXT N#:                   9163 ns     9258 ns     98.97%
    REPEATUNTILTRUE:           4920 ns     4744 ns    103.71%
    WHILEFALSE:ENDWHILE:       4556 ns     4401 ns    103.52%
    A%=FALSE:                  6354 ns     6187 ns    102.70%
    A%=0:                      7626 ns     7477 ns    101.99%
    A=PI:                      8182 ns     8145 ns    100.45%
    ANTIDISESTABLISHMENT=PI:  10634 ns    10482 ns    101.45%
    A=(PI):                   11889 ns    11780 ns    100.93%
    A%=1234567890:            11293 ns    11201 ns    100.82%
    A%=&499602D2:              8531 ns     8398 ns    101.58%
    A=1.23456789E38:          27295 ns    26043 ns    104.81%
    A%=B%:                     8094 ns     7994 ns    101.25%
    A=B:                      11197 ns    11277 ns     99.29%
    ANTI=ANTI:                11685 ns    11771 ns     99.27%
    A%=B%+C%:                 14185 ns    13462 ns    105.37%
    A%=B%-C%:                 14153 ns    13429 ns    105.39%
    A%=B%*C%:                 13957 ns    13124 ns    106.35%
    A%=B%DIVC%:               14112 ns    13387 ns    105.42%
    A%=B%/C%:                 19195 ns    18578 ns    103.32%
    A%=C%^D%:                 26346 ns    25697 ns    102.53%
    A%=B%<<C%:                15533 ns    14752 ns    105.29%
    A%=B%>>C%:                15376 ns    14636 ns    105.06%
    A%=B%>>>C%:               15571 ns    14835 ns    104.96%
    A%%=B%%:                  11636 ns    11720 ns     99.28%
    A%%=B%%+C%%:              19467 ns    19008 ns    102.41%
    A%%=B%%-C%%:              19437 ns    18975 ns    102.43%
    A%%=B%%*C%%:              19271 ns    18667 ns    103.24%
    A%%=B%%DIVC%%:            19362 ns    18900 ns    102.44%
    A%%=B%%/C%%:              26066 ns    25844 ns    100.86%
    A%%=B%%^3:                26746 ns    26673 ns    100.27%
    A%%=B%%<<C%%:             20812 ns    20277 ns    102.64%
    A%%=B%%>>C%%:             20644 ns    20160 ns    102.40%
    A%%=B%%>>>C%%:            20838 ns    20360 ns    102.35%
    A=B+PI:                   17825 ns    17332 ns    102.84%
    A=B-PI:                   17914 ns    17425 ns    102.81%
    A=B*PI:                   18077 ns    17451 ns    103.59%
    A=B/PI:                   17955 ns    17467 ns    102.79%
    A=B^3:                    39716 ns    37683 ns    105.40%
    A=B^PI:                   66378 ns    67485 ns     98.36%
    A=SINB:                   27894 ns    28119 ns     99.20%
    A=TANB:                   30173 ns    30418 ns     99.19%
    A=LOGB:                   25579 ns    24994 ns    102.34%
    A=EXPB:                   20906 ns    21030 ns     99.41%
    A=SQRB:                   15841 ns    15889 ns     99.70%
    A=ATNB:                   32449 ns    32834 ns     98.83%
    A=ABSB:                   12687 ns    12589 ns    100.78%
    A=INTB:                   15030 ns    16642 ns     90.31%
    PROC1:                     4431 ns     4409 ns    100.50%
    A%=FN1:                   21791 ns    21525 ns    101.24%

The worst case is 6.4% slower, and the average is only 1.4% slower.

Given that the check is #ifdef PICO and therefore does not affect any of the other builds I don't think that is unreasonable.

**Comment by rtrussell** [comment]
> Timing results with and without the stack check in bbeval.c
> The worst case is 6.4% slower, and the average is only 1.4% slower.

Oh dear, that's worse than I anticipated.  There's not a chance I could be persuaded to make the change in that case.  I suggest you consider my alternative proposal: estimate a likely maximum stack usage in the expression evaluator (without being a contrived special case) and modify the check in **bbexec.c** to fail if less than that remains free.

Generally I'm not convinced that reporting a fatal error, from which you can't recover, is significantly more valuable than just crashing (or corrupting the display or whatever).  The practical consequence is the same: the program won't run unless it can be modified to use less stack, or more stack space can be made available.

Even [Raymond Chen](https://devblogs.microsoft.com/oldnewthing/) (the Microsoft blogger) argues that it's sometimes better to allow a crash to happen than to attempt to detect and report it, especially if there's no foolproof way to catch it first (which is the case in BBC BASIC).

**Comment by Memotech-Bill** [comment]
> I suggest you consider my alternative proposal: estimate a likely maximum stack usage in the expression evaluator (without being a contrived special case) and modify the check in bbexec.c to fail if less than that remains free.

There is no practical way of doing this. There is no way of knowing how complex an expression a user might wish to evaluate. Any such estimation would have to be contrived, based on the most complex expression possible within the allowed length of a Basic line. Such an estimate would undoubtedly be very conservative and result in unnecessary termination of programs that could otherwise complete without problem.

Any stack check needs to be as close as possible to the point of maximum stack usage.

Would you consider a special compilation option PICO_STACK_CHECKS so that the potential user could decide at compilation time whether or not they wish to include the check? The check could be disabled in your binary distributions.

**Comment by Memotech-Bill** [comment]
> Generally I'm not convinced that reporting a fatal error, from which you can't recover, is significantly more valuable than just crashing (or corrupting the display or whatever). 

The problem is that the program may not crash. If the stack runs into the variables heap it may overwrite variables changing results. If the affected variables are not written to at the same time, the stack will not be corrupted and will subsequently unwind without problem. That could leave an apparently successful program run with spurious results.

**Comment by rtrussell** [comment]
> There is no way of knowing how complex an expression a user might wish to evaluate.

That is correct, but it is not the object of the exercise.  BBC BASIC is not a bomb-proof language; unlike some other BASICs (probably the majority) there are ways in which a BBC BASIC program can fail without generating an error and with the potential for producing false results.  That is inevitably the case with a language that, for example, provides arbitrary memory access via indirection.

So there is no point trying to devise a foolproof way of detecting stack overflow; it's fundamentally impossible anyway because an interrupt may occur at any time and (depending how the interrupt handler is coded) may use an arbitrary amount of machine stack.

So all one can hope for is a scheme that reduces the likelihood of an undetected overflow.  The existing check in **bbexec.c** goes a long way towards that; it currently faults when there is less than 2 Kbytes of free stack space, a 'safety margin' which as far as I'm aware was entirely arbitrary.  Increasing that margin would provide more protection against overflow, at the cost of reduced recursion limit.

BBC BASIC on the Pico is already very slow, and making it even slower (by 6% or more in the worst case) is completely unacceptable to me.  There is no way I can be persuaded to accept a modification with such a consequence.

**Comment by rtrussell** [comment]
I am deleting the Pico-specific stuff from this repository, therefore this issue has become irrelevant.

**Comment by Memotech-Bill** [comment]
I have now implemented a stack protection using the MCU. Details at https://forums.raspberrypi.com/viewtopic.php?p=1935540#p1935540
