### ISSUE TITLE
Require hook to be able to implement *refresh for Pico GUI

### ISSUE THREAD

**Issue by Memotech-Bill** [rtrussell/BBCSDL#19]
In order to implement *refresh for the Pico GUI version it is necessary insert a call where that command is recognised in bbccos.c:

    #ifdef PICO_GUI
    void refresh (const char *p);
    #endif
        :
        :
            case REFRESH:
    #ifdef PICO_GUI
                refresh (p);
    #endif
                return ;

**Comment by rtrussell** [comment]
> In order to implement *refresh for the Pico GUI version it is necessary insert a call where that command
> is recognised in bbccos.c:

Whilst I have no strong feelings about this, I wonder if it's the right approach.  If there are just one or two commands that need to behave differently on the Pico then fine, but what if a situation were to arise when you wanted to **add** one or more **new** commands?   Doing that with the #ifdef PICO mechanism would quickly get messy, and what if a different MCU needed different commands?

Should we consider biting the bullet now and forking **bbccos.c** into multiple target-dependent versions (as we did with **bbccon.c** and **bbpico.c**) rather than shoehorning more and more conditional code into a 'common' version?  Thoughts?

**Comment by rtrussell** [comment]
I am deleting the Pico-specific stuff from this repository, therefore this issue has become irrelevant.
