### ISSUE TITLE
Suggest sound_sdl.c uses standard Pico pin definitions

### ISSUE THREAD

**Issue by Memotech-Bill** [rtrussell/BBCSDL#24]
The Pico SDK includes board definitions for many boards using the RP2040 chip. These use standard defines to identify the pins to use for audio output.

I suggest modifying the pin definitions in sound_sdl.c to be:

    #include "pico.h"
    #if defined(PICO_AUDIO_PWM_L_PIN)
    #define AUDIO_PIN_L    PICO_AUDIO_PWM_L_PIN
    #else
    #define AUDIO_PIN_L    28
    #endif
    #if defined(PICO_AUDIO_PWM_R_PIN)
    #define AUDIO_PIN_R    PICO_AUDIO_PWM_R_PIN
    #else
    #define AUDIO_PIN_R    27
    #endif

**Comment by rtrussell** [comment]
> The Pico SDK includes board definitions for many boards using the RP2040 chip. These use standard defines to identify the pins to use for audio output.

Thanks, that's useful to know.  I won't be modifying the source solely for that reason (as you know, that's a hassle for me because of the way I use GitHub, involving FTP-ing from my Raspberry Pi to my Windows laptop, then transferring to the sandboxed PC using Microsoft OneDrive!) but if it needs to be changed for some other reason it could be incorporated at the same time.
