### ISSUE TITLE
bbcbasic console edition

### ISSUE THREAD

**Issue by antonioleal** [rtrussell/BBCSDL#39]
On the latest release 1.39a I'm getting a segmentation fault. Can you reproduce it?

It happens when I start the program from the command line.

**Comment by rtrussell** [comment]
> On the latest release 1.39a I'm getting a segmentation fault. Can you reproduce it?

Version 1.39a isn't a **Console Mode** edition, it's a **GUI** edition (_BBC BASIC for SDL 2.0_); are you using the wrong executable?  The latest Console Mode release is v0.45.

> It happens when I start the program from the command line.

The usual reason for a segmentation fault when starting from the command line is that you've specified a file in the wrong format.  It **must** be a tokenised (internal format) program with the extension `.bbc`  There is **no** support for running a plain text program (`.bas` file) from the command line.

**Comment by antonioleal** [comment]
Sorry about the incomplete report. What I did was:

1. downloaded the complete github source and build both console and bbcsdl on Slackware 15. bbcsdl works well.

2. but the "console edition",  build with the provided makefile:

    BBCSDL/console/linux/makefile

3. when started with ./bbcbasic from command line is producing a "segmentation fault"

**Comment by rtrussell** [comment]
> 3. when started with ./bbcbasic from command line is producing a "segmentation fault"

OK, sorry for the misunderstanding.  I suggest you try the precompiled Linux binary from the [website](https://www.bbcbasic.co.uk/console/), that will help ascertain whether the problem is your build or something to do with Slackware.  Can you attach a debugger to discover more about where the segfault is occurring?

**Comment by antonioleal** [comment]
The precompiled binary from the website works well. So definetly is a Slackware 15.0 issue which is using gcc 11.2.0

----

(No debugging symbols found in ./bbcbasic)
(gdb) run
Starting program: /mnt/data/antonio/Documents/Workspace/slackware-builds/antonioleal/myslackbuilds/development/bbcsdl/BBCSDL/console/linux/bbcbasic 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00000001003fffff in ?? ()
(gdb) quit

**Comment by rtrussell** [comment]
> The precompiled binary from the website works well. So definetly is a Slackware 15.0 issue which is using gcc 11.2.0

Can you try compiling with a different version of gcc, or with clang?  Failing that, perhaps it would be worth trying a different optimization level, e.g. -Os rather than -O2.

When compiled with gcc, BBC BASIC uses [global register variables](https://gcc.gnu.org/onlinedocs/gcc/Global-Register-Variables.html).  Although they are officially supported, they are rarely used and I have experienced anomalies with some versions of gcc.

**Comment by antonioleal** [comment]
With Slackware I tried the gcc 13.2.0, the -Os option to no effect... for now I will remove console support from the SlackBuild.

Note: I also tried on the same machine with Debian and Mint and both turned out fine.

**Comment by antonioleal** [comment]
// Thanks to Alan Alberghini !

(gdb) run
   Starting program: /tmp/BBCSDL/console/linux/bbcbasic
   [Thread debugging using libthread_db enabled]
   Using host libthread_db library "/lib64/libthread_db.so.1".

   Breakpoint 1, main (argc=1, argv=0x7fffffffdf68) at ../../src /bbccon.c:1683
   1683    int exitcode = 0 ;
   (gdb) next
   1684    void *immediate = NULL ;
   (gdb)
   1715    pthread_t hThread = 0 ;
   (gdb)
   1717            platform = 1 ;
   (gdb)
   1719            void *base = NULL ;
   (gdb)
   1721            while ((MaximumRAM >= MINIMUM_RAM) && (NULL == (base = mymap (MaximumRAM))))
   (gdb)
   1726            if (base != NULL)
   (gdb)
   1727                    userRAM = mmap (base, MaximumRAM, PROT_EXEC | PROT_READ | PROT_WRITE,
   (gdb)

   Program received signal SIGSEGV, Segmentation fault.
   0x00000001003fffff in ?? ()
   (gdb)

As can be seen, the SIGSEGV occurred after trying to step over the mmap function call in bbccon.c at line 1727. By inspecting it in the source file and by looking at the "mmap" man page, one can see that:

  - the MAP_FIXED flag needs some care to be correctly used;
  - the SIGSEGV signal can be the result of "Attempted write into a region mapped as read-only."

I think this means that the "base" address returned by the "mymap" function does not work well in the following "mmap" call with the MAP_FIXED flag, probably due to some memory management kernel settings that are different between Slackware and Debian, like "/proc/sys/vm/mmap_min_addr" (if I remember correctly).

**Comment by rtrussell** [comment]
> I think this means that the "base" address returned by the "mymap" function does not work well in the following "mmap" call with the MAP_FIXED flag, probably due to some memory management kernel settings that are different between Slackware and Debian, like "/proc/sys/vm/mmap_min_addr" (if I remember correctly).

If that is the cause, I do not understand why the pre-compiled binary that you downloaded from my web site works.  That uses exactly the same code, just compiled on a Ubuntu platform rather than on a Slackware platform.   If the contents of **/proc/self/maps** is the underlying issue, surely that ought to affect the downloaded binary in the same way?

I think you said the GUI version _BBC BASIC for SDL 2.0_ runs correctly even when compiled in Slackware, and that uses the same method.  However the relevant code in the GUI version was changed in the last release, whereas that change has not yet propagated to the console version.

If you want, you could try copying the `mymap` routine from `bbcsdl.c` into `bbccon.c` to see if it makes a difference.  That would be helpful to me in planning the next update to the console version.

**Comment by antonioleal** [comment]
Yes the SDL version works well, yesterday I tested the console version on 32 bit slackware and it also works, so its a 64 bit slackware problem.


Following your suggestions on the 64 bit Slackware, I copied the mymap function from bbcsdl.c into bbccon.c  and **it works**!

here is what I replaced on bbccon.c

// #ifdef __linux__
// static void *mymap (unsigned int size)
// {
// 	FILE *fp ;
// 	char line[256] ;
// 	void *start, *finish, *base = (void *) 0x400000 ;
//
// 	fp = fopen ("/proc/self/maps", "r") ;
// 	if (fp == NULL)
// 		return NULL ;
//
// 	while (NULL != fgets (line, 256, fp))
// 	    {
// 		sscanf (line, "%p-%p", &start, &finish) ;
// 		start = (void *)((size_t)start & -0x1000) ; // page align (GCC extension)
// 		if (start >= (base + size))
// 			return base ;
// 		if (finish > (void *)0xFFFFF000)
// 			return NULL ;
// 		base = (void *)(((size_t)finish + 0xFFF) & -0x1000) ; // page align
// 		if (base > ((void *)0xFFFFFFFF - size))
// 			return NULL ;
// 	    }
// 	return base ;
// }
// #endif

// #if defined __LINUX__ || defined __ANDROID__
static void *mymap (uintptr_t size)
{
	FILE *fp ;
	char line[256] ;
	void *start, *finish, *base = (void *) 0x400000 ;

	fp = fopen ("/proc/self/maps", "r") ;
	if (fp == NULL)
		return NULL ;

	while (NULL != fgets (line, 256, fp))
	    {
		sscanf (line, "%p-%p", &start, &finish) ;
		start = (void *)((size_t)start & -0x1000) ; // page align (GCC extension)
		if (start >= (base + size))
			return base ;
		base = (void *)(((size_t)finish + 0xFFF) & -0x1000) ; // page align
	    }
	return base ;
}
// #endif

**Comment by rtrussell** [comment]
> I copied the mymap function from bbcsdl.c into bbccon.c and **it works**!

I have now updated **bbccon.c** accordingly.
