### ISSUE TITLE
QUIT 0 causes a "No room" error

### ISSUE THREAD

**Issue by Rob-McKay** [rtrussell/BBCSDL#7]
In both the console edition (0.32) and desktop version (1.21a)  of BBC Basic for Mac OS both report a "No room" error when executing the statement QUIT 0.

Also QUIT 1 does not seem to set the exit code of the console application. I've not checked for the desktop edition.

**Comment by rtrussell** [comment]
Yes, internally QUIT is handled via the ERROR mechanism so **QUIT n** is equivalent to **ERROR -n** hence QUIT 0 is the same as ERROR 0 which is 'No room'.  This is because both QUIT and ERROR require the interpreter to abort immediately via **longjmp()** and that takes only a single numeric parameter.  To allow QUIT 0 one would need to do something different, perhaps one could make **QUIT n** equivalent to **ERROR NOT(n)** but the issue hasn't arisen before.

Setting the exit code is currently supported only in _BBC BASIC for SDL 2.0_.  I can look into the possibility of supporting it in the Console Mode editions.  I will need to do some reading up to discover how to test it on platforms other than Windows!

**Comment by Rob-McKay** [comment]
Using the console version, executing `echo QUIT  1| ./bbcbasic; echo $?` should run BBC Basic console, enter the immediate mode command `QUIT 1` and then print the return code of the bbcbasic command. In this case 1.

If you use QUIT 0, the bbcbasic executable does not exit - not only in the example above but in general.

The reason why QUIT 0 is important is that on Linux / MacOS / Unix type systems, an exit code of 0 generally indicates success, anything else is usually a failure of some kind.

**Comment by rtrussell** [comment]
Thank you, that's very helpful.  Will the same thing work on a Mac?

**Comment by Rob-McKay** [comment]
Yes, the same commands will work on a Mac.

**Comment by rtrussell** [comment]
I hope the update to the Console Mode editions I pushed today has resolved this.

**Comment by rtrussell** [comment]
Closing this issue since I hope it is resolved.  The fix won't get into the BBCSDL binary downloads until the next release, but can be got sooner by building from the source.

**Comment by Rob-McKay** [comment]
Thanks Richard,

I've built it and it works on my Mac M1
